### ISSUE TITLE
Regular expression look behind not handled in Firefox 68

### ISSUE THREAD

**Issue by jesus2099** [kellnerd/musicbrainz-scripts#11]
It will most probably be a won't fix because I am in a niche use-case, but as it took me much trouble to pin point why the unicode punctuation user script does not work in Firefox for Android 68 (the last version to support user scripts):

Regex lookbehind `(?<=` and negative lookbehind `(?<!` is [not supported before Firefox 78](https://caniuse.com/?search=lookbehind).

Some tr[ai]cks:

- https://stackoverflow.com/questions/7376238/javascript-regex-look-behind-alternative
- https://cmsdk.com/javascript/javascript-negative-lookbehind-equivalent.html

**Comment by kellnerd** [comment]
Oh, interesting that the older versions support lookahead but not lookbehind. I thought I had broken compatibility in #8 when I started supporting non-Latin scripts but this means it was already incompatible right from the start.
It's a shame that Firefox for Android no longer supports all browser extensions, but I fear that I won't start cluttering the code with workarounds and browser version checks.

Below is the relevant code where I replaced all lookbehinds by capturing groups (which do not break my [test cases](https://github.com/kellnerd/musicbrainz-bookmarklets/blob/main/test/guessUnicodePunctuation.js)) and reverted the changes from #8 (which of course breaks the [Greek script test case](https://github.com/kellnerd/musicbrainz-bookmarklets/commit/261bde15cf6622fd41b0bf3030476be02ef5a71b#diff-b5e2855a895594f6e3b8d16954b58d1fac6ab62bdce69a2cf757db94e8332f3cR44) because there is no feasible workaround):

```diff
diff --git a/dist/guessUnicodePunctuation.user.js b/dist/guessUnicodePunctuation.user.js
index 4fafe1d..147aa56 100644
--- a/dist/guessUnicodePunctuation.user.js
+++ b/dist/guessUnicodePunctuation.user.js
@@ -45,15 +45,15 @@
 	}
 
 	const transformationRules = [
-		[/(?<=[^\p{L}\d]|^)"(.+?)"(?=[^\p{L}\d]|$)/ug, '“$1”'], // double quoted text
-		[/(?<=\W|^)'(n)'(?=\W|$)/ig, '’$1’'], // special case: 'n'
-		[/(?<=[^\p{L}\d]|^)'(.+?)'(?=[^\p{L}\d]|$)/ug, '‘$1’'], // single quoted text
+		[/(\W|^)"(.+?)"(?=\W|$)/g, '$1“$2”'], // double quoted text
+		[/(\W|^)'(n)'(?=\W|$)/ig, '$1’$2’'], // special case: 'n'
+		[/(\W|^)'(.+?)'(?=\W|$)/g, '$1‘$2’'], // single quoted text
 		// ... which is enclosed by non-word characters or at the beginning/end of the title
 		// [^\p{L}\d] matches Unicode characters which are neither letters nor digits (\W only works with Latin letters)
 		[/(\d+)"/g, '$1″'], // double primes, e.g. for 12″
 		[/(\d+)'(\d+)/g, '$1′$2'], // single primes, e.g. for 3′42″ but not for 70’s
 		[/'/g, '’'], // ... and finally the apostrophes should be remaining
-		[/(?<!\.)\.{3}(?!\.)/g, '…'], // horizontal ellipsis (but not more than three dots)
+		[/([^\.]|^)\.{3}(?!\.)/g, '$1…'], // horizontal ellipsis (but not more than three dots)
 		[/ - /g, ' – '], // en dash as separator
 		[/(\d{4})-(\d{2})-(\d{2})(?=\W|$)/g, '$1‐$2‐$3'], // hyphens for ISO 8601 dates, e.g. 1987‐07–30
 		[/(\d{4})-(\d{2})(?=\W|$)/g, '$1‐$2'], // hyphen for ISO 8601 partial dates, e.g. 2016-04
```

Maybe I could also use a JavaScript transpiler (in addition to the module bundler I am currently using) in order to build compatible versions for older browsers? But since I have no experience with them and there already is [MBS-11646](https://tickets.metabrainz.org/browse/MBS-11646), a native MBS version might be the better place to expect a wider browser support. Until then you could apply the above patch on Android (copy diff, save it as `firefox-68.patch` and run `git apply firefox-68.patch`).

**Comment by jesus2099** [comment]
Oh yes, there was also this [Unicode property stuff](https://caniuse.com/mdn-javascript_builtins_regexp_property_escapes), that Firefox 68 wouldn't understand.
Thanks for the patch, I will try that! :)

**Comment by jesus2099** [comment]
I tried these 4 lines, it was not enough, I will debug again soon.

**Comment by kellnerd** [comment]
I would place my bet on the [`?.` operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining), sorry...
Maybe I should really use a JS transpiler too, but it requires some work and often outputs ugly code 😅

**Comment by jesus2099** [comment]
I found and removed 2 of them but still no buttons.

I do too much editing on mobile (Firefox 68), more than half.
Too bad for me this script won't work. 😔

I do limit my scripts to classic JavaScript for compatibility.
And also because anyway I really cannot understand jQuery, React, ES6, promise, etc. 🤭
It's not as simple self-explanatory as classic JavaScript.

**Comment by kellnerd** [comment]
You might have missed another occurrence, there should be three.
Maybe give [Babel](https://babeljs.io/repl#?browsers=firefox%2068&fileSize=true&sourceType=script) a try? I just have tested their web app (my configuration parameters are part of the URL) and it looks like nothing but the `?.` operators was changed when I transpiled for Firefox 68, it only ruins my formatting in some places (and improves it in others). Apparently it does not replace the RegeEx lookbehind, but it tries to replace `[^\p{L}\d]` by a list of all matching Unicode characters, so please use the patched version above (with `\W`) if you don't want to triple the size of the code 😄

**Comment by jesus2099** [comment]
Thanks, I will look into that.

The inline Violentmonkey editor is blocking the search I had to search with my eyes only. 🤭

`\p{…}` is, despite its ugly syntax, such a great enhancement! That you have indeed to replace by lots and lots of teachers, because `\L` only supports English.

Off topic:
But the other new JavaScript things are so cryptic and confusing to me.
They are mostly shortcuts that make the code more compact but hard to understand at the same time.

Babel provides a great example of a simple function that becomes something with no added value but completely obscure to understand what it does: arrow function.

```js
// Babel Input: ES2015 arrow function
[1, 2, 3].map(n => n + 1);

// Babel Output: ES5 equivalent
[1, 2, 3].map(function(n) {
  return n + 1;
});
```

**Comment by jesus2099** [comment]
I changed some settings in the Presets, randomly: Unchecked `react` and selected `stage-1` instead of `stage-2`. I don't know what it is by I thought the older the best.

Now `?.` are replaced, but still not `?<`.
But, as far as I know, there is no way to emulate this otherwise…
I will remove them manually.
Ach, I kind of give up, at the moment.
The Babel website does not allow proper paste of the source code on mobile (because of its line numbers), I have to transfer to/from PC/mobile, I'm exploding. 😱 💥 
😉

**Comment by jesus2099** [comment]
There is a supported solution for userscripts on mobile, [I have been using Kiwi Browser for 10 months](https://community.metabrainz.org/t/user-scripts-on-mobile/134406/15?u=jesus2099), now.
No need to maintain Firefox 68 compatibility.
