### ISSUE TITLE
Adding recording relationships is broken

### ISSUE THREAD

**Issue by tigerman325** [kellnerd/musicbrainz-scripts#34]
Since the new changes today (2/28/2023), it no longer is adding the labels to the individual recordings when the boxes are checked. Still works fine on the release.

**Comment by kellnerd** [comment]
Strange, I could swear that I have tested this case after I had rewritten the script for the new relationship editor in #32. The rewritten version has already released been released in January to allow testing with the beta server, so it's been a while since I tested with recording relationships, though.

Unfortunately there is no error message in the browser console although I've wrapped the entire section of code that deals with the recordings in a try/catch-block. Somehow the server still manages to send a useless error report ("e is undefined") to sentry.metabrainz.org, although that should only happen for uncatched errors...

**Comment by kellnerd** [comment]
@mwiencek found the issue, https://github.com/metabrainz/musicbrainz-server/commit/bf0d5ec41c7ddb6c5a8396bf3a64f74acaef9337#diff-09a3af5280de69843eb85e6778af8a4223674267a4f9b69b83faafe23a1acdcd added a new required property which my userscript was missing since then. Thanks for the pointer!

The issue should be fixed by cfb7eae892c426bf38b73d54da1543798c9284af and is included in v2023.3.1.

**Comment by tigerman325** [comment]
Thanks! I just updated and it's working now.
