### ISSUE TITLE
can't install with yarn

### ISSUE THREAD

**Issue by dvirtz** [kellnerd/musicbrainz-scripts#42]
yarn doesn't support the `github:` reference.
```
> yarn add '@kellnerd/musicbrainz-scripts@https://github.com/kellnerd/musicbrainz-scripts.git'
➤ YN0000: · Yarn 4.3.1
➤ YN0000: ┌ Resolution step
➤ YN0001: │ @kellnerd/es-utils@github:kellnerd/es-utils: Failed listing refs
➤ YN0001: │   Repository URL: ssh://git@github.com/kellnerd/es-utils.git
➤ YN0001: │   Fatal Error: Could not read from remote repository.
➤ YN0001: │   Exit Code: 128
➤ YN0000: └ Completed in 9s 539ms
➤ YN0000: · Failed with errors in 9s 567ms
```

**Comment by kellnerd** [comment]
Hmm, strange, your version of yarn seems to understand the `github:` specifier, otherwise it would not be able to resolve it to `ssh://git@github.com/kellnerd/es-utils.git`.
Then it somehow fails to read from GitHub over SSH.

Can you try to clone directly using git and see if that fails as well?
```sh
git clone ssh://git@github.com/kellnerd/es-utils.git
```
It should give you a more concrete error than "Exit Code: 128"

I have never used yarn 4, only the classic yarn v1 for some other projects, where installing this package worked as expected:
```sh
> yarn add '@kellnerd/musicbrainz-scripts@https://github.com/kellnerd/musicbrainz-scripts.git'
yarn add v1.22.22
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 2 new dependencies.
info Direct dependencies
└─ @kellnerd/musicbrainz-scripts@0.8.0
info All dependencies
├─ @kellnerd/es-utils@0.2.0
└─ @kellnerd/musicbrainz-scripts@0.8.0
Done in 6.64s.
```

Although I don't think this issue is specifically related to my package.json, I could replace the `github:` specifier with an explicit git+https URL to avoid SSH if that helps.
Try to install from the [yarn](https://github.com/kellnerd/musicbrainz-scripts/tree/yarn) branch and let me know if that works for you:
```sh
yarn add '@kellnerd/musicbrainz-scripts@https://github.com/kellnerd/musicbrainz-scripts.git#yarn'
```

**Comment by dvirtz** [comment]
Thanks, it works after adding an SSH key to github
